BACKGROUND:
  NUM_VARIATIONS: -1  # -1 means all backgrounds
  DIR: "./data/backgrounds/"

DATA:
  FORMAT: image

DETECTRON:
  DEVICE: cuda
  SCORE_THRESH: 0.6
  NMS_THRESH: 0.2
  CONFIG_FILE: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"

OUTPUT:
  DIR: "./data/output/images/"
  FORMAT: jpg

INPUT:
  DIR: "./data/test_data/"
  FORMAT: jpg

VERBOSITY: 0

